models/Project.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;

/**
 * This is the model class for table "{{%project}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $map
 * @property string $description
 * @property integer $city_id
 * @property integer $region_id
 *
 * @property RealEstate[] $realEstates
 */
class Project extends ActiveRecord {

    public $images;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%project}}';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['comfort_ids'], 'each', 'rule' => ['integer']],
            [['name'], 'unique'],
            [['name', 'created_at', 'updated_at', 'created_by', 'updated_by', 'map', 'city_id', 'region_id'], 'required'],
            [['created_at', 'updated_at', 'created_by', 'updated_by', 'city_id', 'region_id'], 'integer'],
            [['name', 'map'], 'string', 'max' => 255],
            [['description'], 'string'],
            [['images'], 'image', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg', 'maxFiles' => 4, 'minSize' => 10240, 'maxSize' => 10485760],
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => \voskobovich\behaviors\ManyToManyBehavior::className(),
                'relations' => [
                    'comfort_ids' => 'comfort',
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Название проекта'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'map' => Yii::t('app', 'Карта'),
            'description' => Yii::t('app', 'Описание'),
            'city_id' => Yii::t('app', 'Город'),
            'region_id' => Yii::t('app', 'Регион'),
            'comfort_ids'=> Yii::t('app', 'Инфраструктура'),
            'images' => Yii::t('app', 'Изображения'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRealEstates() {
        return $this->hasMany(RealEstate::className(), ['project_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity() {
        return $this->hasOne(City::className(), ['id' => 'city_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion() {
        return $this->hasOne(Region::className(), ['id' => 'region_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComfort() {
        return $this->hasMany(Lookup::className(), ['id' => 'lookup_id'])
                        ->viaTable('{{%project_to_lookup}}', ['project_id' => 'id']);
    }

    public function beforeValidate() {
        $this->created_at = $this->updated_at = time();
        $this->updated_by = Yii::$app->user->id;

        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->id;
        }

        return parent::beforeValidate();
    }

    public static function listAll($keyField = 'id', $valueField = 'name', $asArray = true) {
        $query = static::find();
        if ($asArray) {
            $query->select([$keyField, $valueField])->asArray();
        }

        return ArrayHelper::map($query->all(), $keyField, $valueField);
    }

    public function getProjectPhotos() {
        return $this->hasMany(ProjectPhoto::className(), ['project_id' => 'id'])->orderBy("index");
    }

    public function getProjectSliderPhotos() {
        return $this->hasMany(ProjectPhoto::className(), ['project_id' => 'id'])->where(['head_slider' => 1])->orderBy("index");
    }

    public function upload() {
        if ($this->isNewRecord) {
            return false;
        }
        $baseDir = Yii::getAlias('@webroot/upload/project/' . $this->id);
        FileHelper::createDirectory($baseDir);
        $counter = 0;
        if (!$this->isNewRecord) {
            $counter = ProjectPhoto::find()->orderBy('index DESC')->one()->index + 1;
        }
        foreach ($this->images as $file) {
            $baseName = md5(time() . $file->baseName) . '.' . $file->extension;
            if (!$file->saveAs($baseDir . '/' . $baseName)) {
                return false;
            }
            $photo = new ProjectPhoto();
            $photo->src = Yii::getAlias('/upload/project/' . $this->id) . '/' . $baseName;
            $photo->project_id = $this->id;
            $photo->index = $counter;
            $photo->save();

            $counter++;
        }
        return true;
    }

}

controllers/ProjectController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Project;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\helpers\ContentHelper;
use yii\helpers\ArrayHelper;
use app\models\Region;
use yii\helpers\Html;
use app\models\Translation;
use yii\web\UploadedFile;
use app\models\ProjectSearch;
use yii\filters\AccessControl;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller {

    public $layout = 'admin';

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'except' => ['json-list'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionJsonList() {
        $term = Yii::$app->request->get('term');
        $query = (new Query())->select(['name as label', 'id as value'])->from(Project::tableName())->where(['like', 'name', $term])->all();
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $query;
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionAdmin() {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Project();
        $this->view->registerJs('Main.mapInit("' . ContentHelper::MAP_COORDS_DEFAULT . '", "Title")');
        $model->map = ContentHelper::MAP_COORDS_DEFAULT;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->images = UploadedFile::getInstances($model, 'images');

            if (!$model->upload()) {
                /** @todo Show error? */
            }
            \Yii::$app->session->setFlash('success', \Yii::t('app', 'Запись успешно сохранена'));
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $mapCoords = ($model->map) ? $model->map : ContentHelper::MAP_COORDS_DEFAULT;
        $this->view->registerJs('Main.mapInit("' . $mapCoords . '", "Title")');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->images = UploadedFile::getInstances($model, 'images');

            if (!$model->upload()) {
                /** @todo Show error? */
            }
            \Yii::$app->session->setFlash('success', \Yii::t('app', 'Запись успешно сохранена'));
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model = Project::findOne($id);
        Translation::deleteAll(['model' => $model::className(), 'model_id' => $id]);
        $model->delete();
        $this->redirect(['admin']);
    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAjaxRegion() {
        $model = new Project();
        $model->load(Yii::$app->request->post());
        $regions = Region::find()->where(['city_id' => $model->city_id])->all();

        $options = [
            'prompt' => '- ' . $model->getAttributeLabel('region_id') . ' -',
        ];
        return Html::renderSelectOptions('', ArrayHelper::map($regions, 'id', function ($model) {
                            return Translation::t($model, 'name');
                        }), $options);
    }

}

views/project/_admin_photo.php
<?php

use yii\helpers\Html;
?>

<?php $mainClass = ($model->main) ? "photo-item-main" : ""; ?>

<li id="' . $model->id . '" class="photo-item <?= $mainClass ?>">
    <?= Html::a(Html::img('@web' . $model->src, ['class' => '']), '@web' . $model->src, ['class' => 'photo-item-gallery thumbnail']) ?>
    <div class="text-center">
        <?php
        if (!$model->main) {
            echo Html::a(\Yii::t('app', 'Сделать главной'), ['project-photo/set-main', 'id' => $model->id], ['class' => 'photo-setmain btn btn-primary btn-xs']);
        } else {
            echo Html::button(\Yii::t('app', 'Главное фото'), ['class' => 'photo-setmain btn btn-success btn-xs', 'disabled' => true]);
        }

        if (!$model->head_slider) {
            echo Html::a(\Yii::t('app', 'Показывать в слайдере'), ['project-photo/set-slider', 'id' => $model->id, 'show' => 1], ['class' => 'btn btn-warning btn-xs', 'style' => 'margin-left:20px;']);
        } else {
            echo Html::a(\Yii::t('app', 'Не показывать в слайдере'), ['project-photo/set-slider', 'id' => $model->id, 'show' => 0], ['class' => 'btn btn-warning btn-xs', 'style' => 'margin-left:20px;']);
        }

        echo Html::a(\Yii::t('app', 'Удалить'), ['project-photo/delete', 'id' => $model->id], ['class' => 'btn btn-xs btn-danger', 'style' => 'margin-left:20px;']);
        ?>
    </div>
</li>
<hr />

views/project/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\City;
use app\models\Region;
use app\models\Lookup;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <?php
    $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data',
        ],
    ])
    ?>

    <?= $form->errorSummary([$model]) ?>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?> 
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?=
                    $form->field($model, 'city_id')->dropDownList(ArrayHelper::map(City::find()->all(), 'id', 'name'), [
                        'prompt' => '- ' . $model->getAttributeLabel('city_id') . ' -',
                        'data' => [
                            'ajax-option' => true,
                            'target' => Html::getInputId($model, 'region_id'),
                        ],
                    ])
                    ?>
                </div>
                <div class="col-md-6">
                    <?=
                    $form->field($model, 'region_id')->dropDownList(ArrayHelper::map(Region::find()->where(['city_id' => $model->city_id])->all(), 'id', 'name'), [
                        'prompt' => '- ' . $model->getAttributeLabel('region_id') . ' -',
                        'data' => [
                            'url' => Url::to(['/project/ajax-region']),
                        ],
                    ])
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?=
                    $form->field($model, 'description')->widget(yii\imperavi\Widget::className(), [
                        'options' => [
                            'lang' => 'ru',
                            'minHeight' => 200,
                            'imageUpload' => Url::to([
                                'image/upload',
                                'type' => Inflector::camel2id(StringHelper::basename(get_class($model))),
                                'id' => $model->isNewRecord ? 'tmp' : $model->id
                            ]),
                            /* 'fileUpload' => Url::to([
                              'file/upload',
                              'type' => Inflector::camel2id(StringHelper::basename(get_class($model))),
                              'id' => $model->isNewRecord ? 'new' : $model->id
                              ]), */
                            'uploadImageFields' => [
                                Yii::$app->request->csrfParam => Yii::$app->request->csrfToken,
                            ],
                            'convertImageLinks' => true,
                            'convertVideoLinks' => true,
                            //'imageGetJson' => Url::to(['/admin/gallery/json-list']),
                            //'imageManagerJson' => Url::to(['/admin/gallery/json-list']),
                            //'fileManagerJson' => Url::to(['/admin/gallery/json-list']),
                            'imageUploadCallback' => $model->isNewRecord ? new \yii\web\JsExpression(<<<JS
                function(image, json) {
                    $(".page-form")
                        .find('form')
                        .append($('<input type="hidden" name="images[]" value="" />').val($(image).attr("src")));
                }
JS
                                    ) : false,
                        //'definedLinks' => '/defined-links.json', // @todo Action to site pages
                        ],
                        'plugins' => [
                            'fullscreen',
                            'table',
                            'video',
                            'imagemanager',
                            'filemanager',
                            'definedlinks',
                            'fontsize',
                            'fontfamily',
                            'fontcolor',
                        //'clips',
                        ]
                    ])
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'map')->hiddenInput(['maxlength' => true, 'class' => 'hiddenCoords']) ?>
                    <div id="map" style="width: 100%; height: 400px; margin-bottom: 20px;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <p class="text-bold"><?= \Yii::t('app', 'Фотографии (размер фото от 10кб до 10мб)') ?></p>
                        </div>
                        <div class="panel-body">
                            <ul id="sortable" style="padding-left: 0px;">
                                <?php
                                $photos = $model->getProjectPhotos()->all();
                                foreach ($photos as $photo) {
                                    echo $this->render('_admin_photo', [
                                        'model' => $photo
                                    ]);
                                }
                                ?>
                            </ul>

                            <?= $form->field($model, 'images[]')->fileInput(['multiple' => true]) ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $form->field($model, 'comfort_ids')->checkBoxList(Lookup::items(Lookup::TYPE_HOUSING_COMFORT, true), ['multiple' => true]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/project/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\City;
use app\models\Region;

$this->title = Yii::t('app', 'Проекты');
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

<p>
    <?= Html::a(Yii::t('app', 'Добавить проект'), ['create'], ['class' => 'btn btn-success']) ?>
</p>
<?=
GridView::widget([
    'filterModel' => $searchModel,
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'name',
        [
            'attribute' => 'city_id',
            'filter' => City::find()->select(['name', 'id'])->indexBy('id')->column(),
            'value' => function ($data) {
        if (isset($data->city->name)) {
            return $data->city->name;
        } else {
            return $data->city_id;
        }
    }
        ],
        [
            'attribute' => 'region_id',
            'filter' => Region::find()->select(['name', 'id'])->indexBy('id')->column(),
            'value' => function ($data) {
        if (isset($data->region->name)) {
            return $data->region->name;
        } else {
            return $data->region_id;
        }
    }
        ],
        [
            'class' => \yii\grid\ActionColumn::className(),
            'template' => '{update} {delete}',
        ],
    ],
])
?>

views/project/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Page */

$this->title = Yii::t('app', 'Добавить проект');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Проекты'), 'url' => ['admin']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/project/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Page */

$this->title = Yii::t('app', 'Редактирование проекта') . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Проекты'), 'url' => ['admin']];
$this->params['breadcrumbs'][] = $model->name;
//$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="page-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>