modules/rbac/controllers/RoleController.php
<?php

namespace app\modules\rbac\controllers;

use app\modules\rbac\models\AssignmentForm;
use app\modules\rbac\Module;
use app\models\AuthItem;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class RoleController extends Controller
{
    public function actionIndex()
    {
        //Yii::$app->authManager->getRoles();
        $query = AuthItem::find()->where(['type' => 1]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdate($id) {
        $model = AuthItem::findOne(['name' => $id]);
        if($model) {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {

            }
            return $this->render('update', ['model' => $model]);
        }
    }

    public function actionCreate() {
        $model = new AuthItem();
        if ($model->load(Yii::$app->request->post())) {
            $model->type = 1;
            if($model->save()) {
                return $this->redirect(['update', 'id' => $model->name]);
            }
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionAddChild() {
        $data = Yii::$app->request->post();

        $parentRole = Yii::$app->authManager->getRole($data['parentRole']);
        $childRole = Yii::$app->authManager->getRole($data['childRole']);

        if(!Yii::$app->authManager->hasChild($parentRole, $childRole) && !Yii::$app->authManager->hasChild($childRole, $parentRole)) {
            Yii::$app->authManager->addChild($parentRole, $childRole);
        }
        $this->redirect(['role/update', 'id' => $data['parentRole']]);
    }

    public function actionDeleteChild($parentRole, $childRole) {
        $parent = Yii::$app->authManager->getRole($parentRole);
        $child = Yii::$app->authManager->getRole($childRole);
        Yii::$app->authManager->removeChild($parent, $child);
        $this->redirect(['role/update', 'id' => $parentRole]);
    }


    public function actionDelete($id) {
        $model = AuthItem::findOne(['name' => $id]);
        if($model) {
            $role = Yii::$app->authManager->getRole($model->name);
            Yii::$app->authManager->removeChildren($role);
            $model->delete();
        }
        return $this->redirect(['index']);
    }
}

modules/rbac/views/role/create.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yiicms\widgets\Select2;
use app\models\AuthItem;
use app\models\Translation;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = Yii::t('app', 'Создание роли');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Roles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Новая роль');
?>
<div class="assignment-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-md-12">
            <?php $form = ActiveForm::begin(); ?>
            <?= $form->errorSummary($model) ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-bold"><?= Yii::t('app', 'Новая роль') ?></p>
                </div>
                <div class="panel-body">

                    <div class="form-group">
                        <?= $form->field($model, 'name')->textInput() ?>
                    </div>

                    <div class="form-group">
                        <?= $form->field($model, 'description')->textInput() ?>
                    </div>
                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/rbac/views/role/index.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel \yii\base\Model|null */

$this->title = Yii::t('app', 'Роли');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <?= Html::a(Yii::t('app', 'Новая роль'), ['create'], ['class' => 'btn btn-success']) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'description',
            'name',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
            ],
        ],
    ]); ?>

</div>

modules/rbac/views/role/update.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yiicms\widgets\Select2;
use app\models\AuthItem;
use app\models\Translation;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = Yii::t('app', 'Роль {role}', ['role' => Translation::t($model, 'description')]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Roles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="assignment-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-bold"><?= Translation::t($model, 'description') ?></p>
                </div>
                <div class="panel-body">
                    <?php $form = ActiveForm::begin(); ?>

                    <div class="form-group">
                        <?= $form->field($model, 'name')->textInput(['disabled' => 'disabled']) ?>
                    </div>

                    <div class="form-group">
                        <?= $form->field($model, 'description')->textInput() ?>
                    </div>
                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="text-bold"><?= Yii::t('app', 'Дочерние роли') ?></p>
                </div>
                <div class="panel-body">
                    <?= Html::beginForm(['role/add-child']) ?>
                    <div class="form-group">
                        <ul>
                            <?php foreach($model->getChildren()->where(['type' => 1])->all() as $childRole) { ?>
                                <li><?= $childRole->description . ' (' . $childRole->name . ')' ?> <?= Html::a(Yii::t('app', 'удалить'), ['delete-child', 'parentRole' => $model->name, 'childRole' => $childRole->name]) ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="form-group">
                        <?= Html::hiddenInput('parentRole', $model->name) ?>
                        <?= Html::dropDownList('childRole', null, ArrayHelper::map(AuthItem::find()->where(['type' => 1])->andWhere(['<>', 'name', $model->name])->all(), 'name', 'description'), ['class' => 'form-control']) ?>
                    </div>
                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' => 'btn btn-primary']) ?>
                    </div>
                    <?= Html::endForm() ?>
                </div>
            </div>
        </div>
    </div>
</div>