controllers/AlbumController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ImageAlbum;
use app\models\ImageToAlbum;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class AlbumController extends \yii\web\Controller {

    public $layout = 'admin';

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionAdmin() {
        $dataProvider = new ActiveDataProvider([
            'query' => ImageAlbum::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        return $this->render('admin', [
                    'dataProvider' => $dataProvider
        ]);
    }

    public function actionCreate() {
        $model = new ImageAlbum();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->session->setFlash('success', \Yii::t('app', 'Запись успешно сохранена'));
        }

        return $this->render('create', [
                    'model' => $model
        ]);
    }

    public function actionUpdate($id) {
        $model = ImageAlbum::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->session->setFlash('success', \Yii::t('app', 'Запись успешно сохранена'));
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $model = ImageAlbum::findOne($id);
        $model->delete();
        $this->redirect(['album/admin']);
    }

    public function actionSetImageOrderDown($imageId, $albumId) {
        $relation = ImageToAlbum::findOne(['image_id' => $imageId, 'album_id' => $albumId]);

        if ($relation) {
            $currentOrder = $relation->order;
            $nextRelation = ImageToAlbum::findOne(['image_id' => $imageId, 'album_id' => $albumId, 'order' => $currentOrder++]);

            if ($nextRelation) {
                ImageToAlbum::updateAll(["order" => $nextRelation->order], "album_id = $albumId AND image_id = $imageId");
                ImageToAlbum::updateAll(["order" => $currentOrder], "album_id = $albumId AND image_id = $nextRelation->image_id");
            }
        }

        return $this->redirect(['update', 'id' => $albumId]);
    }

    public function actionSetImageOrderUp($imageId, $albumId) {
        $relation = ImageToAlbum::findOne(['image_id' => $imageId, 'album_id' => $albumId]);

        if ($relation) {
            $currentOrder = $relation->order;
            $nextRelation = ImageToAlbum::findOne(['image_id' => $imageId, 'album_id' => $albumId, 'order' => $currentOrder--]);

            if ($nextRelation) {
                ImageToAlbum::updateAll(["order" => $nextRelation->order], "album_id = $albumId AND image_id = $imageId");
                ImageToAlbum::updateAll(["order" => $currentOrder], "album_id = $albumId AND image_id = $nextRelation->image_id");
            }
        }

        return $this->redirect(['update', 'id' => $albumId]);
    }

}

views/album/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin() ?>
<?= $form->errorSummary([$model]) ?>
<div class="row">
    <div class="col-md-12">
        <?php echo $form->field($model, 'name')->textInput() ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?=
        Html::submitButton(($model->getIsNewRecord()) ? \Yii::t('app', 'Создать') : \Yii::t('app', 'Сохранить'), [
            'class' => 'btn btn-success'
        ]);
        ?>
    </div>
</div>
<?php if (!$model->getIsNewRecord()) { ?>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-12">
            <h1><?php echo \Yii::t('app', 'Сортировка изображений'); ?></h1>
            <?php
            echo Html::beginTag('table', ['class' => 'table table-striped table-bordered']);
            $a = 0;
            foreach ($model->albumImages as $image) {
                $a++;

                echo Html::beginTag('tr');
                echo Html::beginTag('td');
                echo Html::img('@web/upload/' . $image->image, ['alt' => $image->image, 'class' => 'gridImage']);
                echo Html::endTag('td');
                echo Html::beginTag('td');
                $buttonUp = Html::a('<span class="glyphicon glyphicon-upload"></span>', ['/album/set-image-order-up', 'imageId' => $image->id, 'albumId' => $model->id]);
                $buttonDown = Html::a('<span class="glyphicon glyphicon-download"></span>', ['/album/set-image-order-down', 'imageId' => $image->id, 'albumId' => $model->id]);

                if ($a == 1) {
                    echo $buttonDown;
                } else if ($a == count($model->albumImages)) {
                    echo $buttonUp;
                } else {
                    echo $buttonDown;
                    echo $buttonUp;
                }
                echo Html::endTag('td');
                echo Html::endTag('tr');
            }
            echo Html::endTag('table');
            ?>
        </div>
    </div>
<?php } ?>
<?php ActiveForm::end(); ?>

views/album/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Альбомы');
$this->params['breadcrumbs'][] = $this->title;
?>


<h1><?= Html::encode($this->title) ?></h1>

<p>
    <?= Html::a(Yii::t('app', 'Добавить альбом'), ['create'], ['class' => 'btn btn-success']) ?>
</p>
<?=
GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'name',
        [
            'attribute' => 'imagesCount',
            'value' => function ($data) {
                return count($data->getImageToAlbums()->asArray()->all());
            }
        ],
        [
            'class' => \yii\grid\ActionColumn::className(),
            'template' => '{update} {delete}',
        ],
    ],
])
?>

views/album/create.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('app', 'Добавить альбом');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Альбомы'), 'url' => ['admin']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="album-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/album/update.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('app', 'Изменить альбом');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Альбомы'), 'url' => ['admin']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Изменить');
?>
<div class="album-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>